//
// Generated by Bluespec Compiler, version 2012.01.A (build 26572, 2012-01-17)
//
// On Wed Aug 14 13:16:03 BST 2013
//
// Method conflict info:
// Method: filter
// Conflict-free: hsync, vde
// Sequenced before (restricted): bin_out
// Conflicts: filter
//
// Method: bin_out
// Conflict-free: bin_out, hsync
// Sequenced after (restricted): filter, vde
//
// Method: hsync
// Conflict-free: filter, bin_out, vde
// Conflicts: hsync
//
// Method: vde
// Conflict-free: filter, hsync
// Sequenced before (restricted): bin_out
// Conflicts: vde
//
//
// Ports:
// Name                         I/O  size props
// bin_out                        O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// bin_in                         I     1
// hsync                          I     1
// vde                            I     1
//
// Combinational paths from inputs to outputs:
//   (bin_in, vde) -> bin_out
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
`define BSV_ASSIGNMENT_DELAY
`endif

module mkEdge(CLK,
	      RST_N,

	      bin_in,

	      bin_out,

	      hsync,

	      vde);
  input  CLK;
  input  RST_N;

  // action method filter
  input  bin_in;

  // value method bin_out
  output bin_out;

  // action method hsync
  input  hsync;

  // action method vde
  input  vde;

  // signals for module outputs
  wire bin_out;

  // inlined wires
  wire filtered$wget, filtered$whas;

  // register lastRow
  reg [1279 : 0] lastRow;
  wire [1279 : 0] lastRow$D_IN;
  wire lastRow$EN;

  // register ready
  reg ready;
  wire ready$D_IN, ready$EN;

  // register x
  reg [10 : 0] x;
  wire [10 : 0] x$D_IN;
  wire x$EN;

  // rule scheduling signals
  wire WILL_FIRE_RL_new_pixel;

  // inputs to muxes for submodule ports
  wire [10 : 0] MUX_x$write_1__VAL_1;

  // remaining internal signals
  wire [1279 : 0] x__h589, y__h633;
  wire x__h534, y__h535;

  // value method bin_out
  assign bin_out = filtered$whas && filtered$wget ;

  // rule RL_new_pixel
  assign WILL_FIRE_RL_new_pixel = vde && !hsync && ready ;

  // inputs to muxes for submodule ports
  assign MUX_x$write_1__VAL_1 = x + 11'd1 ;

  // inlined wires
  assign filtered$wget = x__h534 & y__h535 ;
  assign filtered$whas = vde && ready ;

  // register lastRow
  assign lastRow$D_IN = bin_in ? lastRow | x__h589 : lastRow & y__h633 ;
  assign lastRow$EN = filtered$whas ;

  // register ready
  assign ready$D_IN = 1'd1 ;
  assign ready$EN = hsync && !ready ;

  // register x
  assign x$D_IN = WILL_FIRE_RL_new_pixel ? MUX_x$write_1__VAL_1 : 11'd0 ;
  assign x$EN = WILL_FIRE_RL_new_pixel || hsync && x != 11'd0 && ready ;

  // remaining internal signals
  assign x__h534 = lastRow[x] ;
  assign x__h589 = 1280'd1 << x ;
  assign y__h535 = ~bin_in ;
  assign y__h633 = ~x__h589 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (!RST_N)
      begin
        lastRow <= `BSV_ASSIGNMENT_DELAY 1280'd0;
	ready <= `BSV_ASSIGNMENT_DELAY 1'd0;
	x <= `BSV_ASSIGNMENT_DELAY 11'd0;
      end
    else
      begin
        if (lastRow$EN) lastRow <= `BSV_ASSIGNMENT_DELAY lastRow$D_IN;
	if (ready$EN) ready <= `BSV_ASSIGNMENT_DELAY ready$D_IN;
	if (x$EN) x <= `BSV_ASSIGNMENT_DELAY x$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    lastRow =
	1280'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    ready = 1'h0;
    x = 11'h2AA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkEdge

