//
// Generated by Bluespec Compiler, version 2012.01.A (build 26572, 2012-01-17)
//
// On Tue Mar 26 13:22:55 GMT 2013
//
// Method conflict info:
// Method: filter
// Conflicts: filter
//
//
// Ports:
// Name                         I/O  size props
// gry_out                        O     8
// CLK                            I     1 unused
// RST_N                          I     1 unused
// rgb_in                         I    24
//
// Combinational paths from inputs to outputs:
//   rgb_in -> gry_out
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
`define BSV_ASSIGNMENT_DELAY
`endif

module mkGreyscale(CLK,
		   RST_N,

		   rgb_in,
		   gry_out);
  input  CLK;
  input  RST_N;

  // actionvalue method filter
  input  [23 : 0] rgb_in;
  output [7 : 0] gry_out;

  // signals for module outputs
  wire [7 : 0] gry_out;

  // remaining internal signals
  wire [9 : 0] _0_CONCAT_b38_BITS_9_TO_1_MINUS_127__q1, b__h738;

  // actionvalue method filter
  assign gry_out = _0_CONCAT_b38_BITS_9_TO_1_MINUS_127__q1[7:0] ;

  // remaining internal signals
  assign _0_CONCAT_b38_BITS_9_TO_1_MINUS_127__q1 =
	     { 1'd0, b__h738[9:1] } - 10'd127 ;
  assign b__h738 =
	     { 2'd0, rgb_in[23:16] } + { 2'd0, rgb_in[15:8] } +
	     { 2'd0, rgb_in[7:0] } ;
endmodule  // mkGreyscale

