//
// Generated by Bluespec Compiler, version 2012.01.A (build 26572, 2012-01-17)
//
// On Thu Mar 28 19:30:05 GMT 2013
//
// Method conflict info:
// Method: filter
// Conflicts: filter
//
//
// Ports:
// Name                         I/O  size props
// gry_out                        O     8
// CLK                            I     1 unused
// RST_N                          I     1 unused
// rgb_in                         I    24
//
// Combinational paths from inputs to outputs:
//   rgb_in -> gry_out
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
`define BSV_ASSIGNMENT_DELAY
`endif

module mkGreyscale(CLK,
		   RST_N,

		   rgb_in,
		   gry_out);
  input  CLK;
  input  RST_N;

  // actionvalue method filter
  input  [23 : 0] rgb_in;
  output [7 : 0] gry_out;

  // signals for module outputs
  wire [7 : 0] gry_out;

  // remaining internal signals
  wire [8 : 0] _0_CONCAT_rgb_in_BITS_15_TO_8_PLUS_0_CONCAT_rgb_ETC__q1,
	       b51_PLUS_0_CONCAT_rgb_in_BITS_23_TO_16__q2,
	       b__h751;

  // actionvalue method filter
  assign gry_out = b51_PLUS_0_CONCAT_rgb_in_BITS_23_TO_16__q2[8:1] ;

  // remaining internal signals
  assign _0_CONCAT_rgb_in_BITS_15_TO_8_PLUS_0_CONCAT_rgb_ETC__q1 =
	     { 1'd0, rgb_in[15:8] } + { 1'd0, rgb_in[7:0] } ;
  assign b51_PLUS_0_CONCAT_rgb_in_BITS_23_TO_16__q2 =
	     b__h751 + { 1'd0, rgb_in[23:16] } ;
  assign b__h751 =
	     { 1'd0,
	       _0_CONCAT_rgb_in_BITS_15_TO_8_PLUS_0_CONCAT_rgb_ETC__q1[8:1] } ;
endmodule  // mkGreyscale

