//
// Generated by Bluespec Compiler, version 2012.01.A (build 26572, 2012-01-17)
//
// On Sun Mar 31 15:57:08 BST 2013
//
// Method conflict info:
// Method: filter
// Conflicts: filter
//
//
// Ports:
// Name                         I/O  size props
// rgb_out                        O    24
// CLK                            I     1 unused
// RST_N                          I     1 unused
// bin_in                         I     1
// rgb_in                         I    24
//
// Combinational paths from inputs to outputs:
//   (bin_in, rgb_in) -> rgb_out
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
`define BSV_ASSIGNMENT_DELAY
`endif

module mkMix(CLK,
	     RST_N,

	     bin_in,
	     rgb_in,
	     rgb_out);
  input  CLK;
  input  RST_N;

  // actionvalue method filter
  input  bin_in;
  input  [23 : 0] rgb_in;
  output [23 : 0] rgb_out;

  // signals for module outputs
  wire [23 : 0] rgb_out;

  // inlined wires
  wire [7 : 0] blue$wget, green$wget, red$wget;

  // actionvalue method filter
  assign rgb_out = { red$wget, green$wget, blue$wget } ;

  // inlined wires
  assign red$wget = bin_in ? 8'd255 : { 2'd0, rgb_in[23:18] } ;
  assign green$wget = bin_in ? 8'd255 : { 2'd0, rgb_in[15:10] } ;
  assign blue$wget = bin_in ? 8'd255 : { 2'd0, rgb_in[7:2] } ;
endmodule  // mkMix

