//
// Generated by Bluespec Compiler, version 2012.01.A (build 26572, 2012-01-17)
//
// On Fri Mar 29 18:33:13 GMT 2013
//
// Method conflict info:
// Method: filter
// Sequenced before (restricted): gry_out, bin_out
// Conflicts: filter
//
// Method: gry_out
// Conflict-free: gry_out, bin_out
// Sequenced after (restricted): filter
//
// Method: bin_out
// Conflict-free: gry_out, bin_out
// Sequenced after (restricted): filter
//
//
// Ports:
// Name                         I/O  size props
// gry_out                        O     8
// bin_out                        O     1
// CLK                            I     1 unused
// RST_N                          I     1 unused
// gry_in                         I     8
//
// Combinational paths from inputs to outputs:
//   gry_in -> gry_out
//   gry_in -> bin_out
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
`define BSV_ASSIGNMENT_DELAY
`endif

module mkThreshold(CLK,
		   RST_N,

		   gry_in,

		   gry_out,

		   bin_out);
  parameter [7 : 0] threshold = 8'b0;
  input  CLK;
  input  RST_N;

  // action method filter
  input  [7 : 0] gry_in;

  // value method gry_out
  output [7 : 0] gry_out;

  // value method bin_out
  output bin_out;

  // signals for module outputs
  wire [7 : 0] gry_out;
  wire bin_out;

  // inlined wires
  wire belowThreshold$wget;

  // value method gry_out
  assign gry_out = belowThreshold$wget ? 8'd0 : 8'd255 ;

  // value method bin_out
  assign bin_out = !belowThreshold$wget ;

  // inlined wires
  assign belowThreshold$wget = gry_in < threshold ;
endmodule  // mkThreshold

